config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  resources :quotes do
    resources :line_item_dates, except: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true

  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  belongs_to :quote

  validates :date, presence: true, uniqueness: { scope: :quote_id }

  scope :ordered, -> { order(date: :asc) }
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  has_many :line_item_dates, dependent: :destroy

  validates :name, presence: true
  scope :ordered, -> { order(id: :desc) }

  # after_create_commit lambda {
  #                       broadcast_prepend_later_to 'quotes', partial: 'quotes/quote', locals: { quote: self }
  #                     }

  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }
  # The above three callbacks are equivalent to the following single line
  broadcasts_to ->(quote) { [quote.company, 'quotes'] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :company
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]

  def index
    @quotes = current_company.quotes.ordered if current_company
  end

  def show
    @line_item_dates = @quote.line_item_dates.ordered
    p @line_item_dates.inspect
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: 'Quote was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Quote was succesfully updated.' }
      end

    else
      p 'something to print'
      p @quote.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: 'Quote was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Quote was successfully destroyed.' }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" style="font-size: var(--font-size-s);
    color: var(--color-white);
    padding: var(--space-xs) var(--space-m);
    background-color: var(--color-dark);
    animation: appear-then-fade 4s both;
    border-radius: 999px;">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar" style="display: flex;
  align-items: center;
  box-shadow: var(--shadow-large);
  padding: var(--space-xs) var(--space-m);
  margin-bottom: var(--space-xxl);
  background-color: (var(--color-white));">
  <% if user_signed_in? %>
    <div class="navbar__brand" style="font-weight: bold;
    font-size: var(--font-size-xl);
    color: var(--color-text-header);">
      <%= current_company.name unless !current_company %>
    </div>
    <div class="navbar__name" style="font-weight: bold;
    margin-left: auto;
    margin-right: var(--space-s);
    color: var(--color-text-header);">
      <%= current_user.name %>
    </div>
    <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>


    <%= turbo_frame_tag "flash" do %>
      <%= render "layouts/flash" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/line_item_dates/_line_item_date.html.erb
<div class="line-item-date" style="margin-top: var(--space-xl);
  margin-bottom: var(--space-xxs);">
  <div class="line-item-date__header" style="display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-xs);">
    <h2 class="line-item-date__title" style="font-size: var(--font-size-xl);">
      <%= l(line_item_date.date, format: :long) %>
    </h2>

    <div class="line-item-date__actions" style="display: flex;
    gap: var(--space-xs);">
      <%= button_to "Delete",
                    # same as: quote_line_item_date_path(quote, line_item_date)
                    [quote, line_item_date],
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  [:edit, quote, line_item_date],
                  class: "btn btn--light" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<main class="container">
  <h1>Quote editor</h1>
  <p>A blazing fast quote editor built with Hotwire</p>

  <% if user_signed_in? %>
    <%= link_to "View quotes", quotes_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</main>

app/views/quotes/_empty_state.html.erb
<div class="empty-state" sytle="padding: var(--space-m);
  border: var(--border);
  border-style: dashed;
  text-align: center;">
  <p class="empty-state__text" style="font-size: var(--font-size-l);
    color: var(--color-text-header);
    margin-bottom: var(--space-l);
    font-weight: bold; ">
    You don't have any quotes yet!
  </p>

  <%= link_to "Add quote", new_quote_path, class: "btn btn--primary" %>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>

  <%= f.submit class: "btn btn--secondary" %>

  <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <%= link_to quote.name,
                quote_path(quote),
                data: { turbo_frame: "_top" } %>

    <div class="quote__actions">
      <%= button_to "Delete",
                    quote_path(quote),
                    method: :delete,
                    class: "btn btn--light" %>

      <%= link_to "Edit",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %>
<%# same as this: <%= turbo_stream.prepend "quotes", @quote %>
<%# <%= turbo_stream.prepend "quotes" do %>
  <%# <%= render @quote %>
<%# <% end %>

<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

<% unless current_company.quotes.exists? %>
  <%= turbo_stream.update Quote.new do %>
    <%= render partial: "quotes/empty_state" %>
  <% end %>
<% end %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>

  <%# frame_tag automatically passes given obj to dom_id. in short: id=quote.id %>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, "quotes" %>

<main class="container">
  <div class="header">
    <h1>Quotes</h1>

    <%= link_to "New quote",
                new_quote_path,
                class: "btn btn--primary",
                # 'new_quote' === dom_id(Quote.new)
                data: { turbo_frame: 'new_quote' } %>
  </div>

  <%# Quote.new === 'new_quote' %>
  <%= turbo_frame_tag Quote.new do %>
    <% if !@quotes || @quotes.none? %>
      <%= render partial: 'quotes/empty_state' %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag 'quotes' do %>
    <%= render @quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%# similar to index.html, here @quote can be 'new_quote' %>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>

    <%= link_to 'New Date',
                new_quote_line_item_date_path(@quote),
                class: "btn btn--primary" %>
  </div>

  <%= render @line_item_dates, quote: @quote %>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>